-- 저자 별 카테고리 별 매출액 집계하기
SELECT 
    B.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY, 
    SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM 
    BOOK_SALES S
JOIN 
    BOOK B 
ON 
    S.BOOK_ID = B.BOOK_ID
JOIN 
    AUTHOR A 
ON 
    B.AUTHOR_ID = A.AUTHOR_ID
WHERE 
    S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY 
    B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY 
    B.AUTHOR_ID ASC, 
    B.CATEGORY DESC;