-- 대여 기록이 존재하는 자동차 리스트 구하기
SELECT DISTINCT
    C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
  ON C.CAR_ID = CH.CAR_ID
WHERE
  C.CAR_TYPE = '세단'
  AND MONTH(CH.START_DATE) = 10
ORDER BY C.CAR_ID DESC;